### ISSUE TITLE
[Bug] : Connection.h: No such file or directory

### ISSUE THREAD

**Issue by alazifi** [CoreX-IoT/corex-firmware#44]
I tried an example from CoreX Library in Arduino IDE, File > Examples > CoreX > Espressif > ReceiveLED, and it works normally.

But if i copy the code to new sketch and compile it, the output log show:

Connection.h: No such file or directory.

**Comment by krnt-27** [comment]
because Connection.h is located in another file. you must include also Connection.h file and call it on main file (.ino)
